# Generated by Django 5.1.7 on 2025-03-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allergies',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
