# Generated by Django 5.1.7 on 2025-03-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_allergies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allergies',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
